import os

SAMPLE_RATE = 16000
VAD_WINDOW = 512  # 약 32ms (Silero VAD 권장 사이즈)
CHANNELS = 1
PRE_ROLL_SECONDS = 0.5
MAX_UTTERANCE_SECONDS = 30
PARTIAL_UPDATE_INTERVAL_SECONDS = float(os.getenv("PARTIAL_UPDATE_INTERVAL_SECONDS", "1.0"))
MIN_PARTIAL_AUDIO_SECONDS = float(os.getenv("MIN_PARTIAL_AUDIO_SECONDS", "1.0"))
END_GRACE_SECONDS = float(os.getenv("END_GRACE_SECONDS", "0.6"))
STABLE_WORD_COUNT_THRESHOLD = int(os.getenv("STABLE_WORD_COUNT_THRESHOLD", "3"))
STABLE_WORD_AGE_SECONDS = float(os.getenv("STABLE_WORD_AGE_SECONDS", "0.3"))
DEFAULT_LANGUAGE = os.getenv("WHISPER_LANGUAGE", "ko")
WHISPER_CPP_BIN = os.getenv("WHISPER_CPP_BIN", "")
WHISPER_MODEL_PATH = os.getenv("WHISPER_MODEL_PATH", "")
WHISPER_NO_GPU = os.getenv("WHISPER_NO_GPU", "1") != "0"
